### ISSUE TITLE
minor documentation issue: `--assignment` argument doesn't work with `fetch-scores`

### ISSUE THREAD

**Issue by lkuper** [edulinq/py-canvas#12]
I'm using the version installed with `pip install`, and it looks like the documentation for `fetch-scores` is not quite accurate.  The examples in the README use an `--assignment` argument:

```
python3 -m canvas.cli.assignment.fetch-scores --assignment 123456

python3 -m canvas.cli.assignment.fetch-scores --assignment 'My Assignment'
```

But that's not what the usage message says:

```
$ python3 -m canvas.cli.assignment.fetch-scores --assignment 'Assignment 1'
usage: fetch-scores.py [-h] [--config CONFIG_PATHS] [--log-level {DEBUG,INFO,WARNING,ERROR,CRITICAL}] [--server SERVER] [--token TOKEN] [--course COURSE] [--skip-headers] assignment
fetch-scores.py: error: unrecognized arguments: --assignment
```

(If I leave out `--assignment`, it works fine.)

**Comment by eriq-augustine** [comment]
Yup, you are correct.

We have an old flag there.
Documentation just updated in 1eda6c750904dffb49a5d1cd07923f1c5a06203c.

Thanks for the find.
